export interface MessageTypes {
  ERROR_STATUS_NULL: string

  ERROR_AUTH_FLAG_ACCESS: string
  ERROR_AUTH_FLAG_OPERATE: string
  ERROR_BYLOND_LEVEL_OPERATE: string
  ERROR_VALID_IDMARK_NOTEXIST: string
  ERROR_AUTH_OPERATE_GROUP_NULL: string

  ERROR_UPLOAD_FILE_MIMETYPE: string
  ERROR_UPLOAD_FILESIZE_LARGEMAX: string
  ERROR_UPLOAD_NOT_FILE: string

  ERROR_LOGINVALID_FAIL: string

  ERROR_VALID_USERNAME_REQUIRED: string
  ERROR_VALID_USERNAME_FORMAT: string
  ERROR_VALID_USERNAME_UNIQUE: string
  ERROR_VALID_PASSWORD_REQUIRED: string
  ERROR_VALID_PASSWORD_FORMAT: string
  ERROR_VALID_EMAIL_REQUIRED: string
  ERROR_VALID_EMAIL_FORMAT: string
  ERROR_VALID_EMAIL_UNIQUE: string
  ERROR_VALID_TICKET_REQUIRED: string
  ERROR_VALID_TICKET_NULL: string
  ERROR_VALID_TICKET_TYPE: string
  ERROR_VALID_TICKET_USED: string
  ERROR_VALID_TICKET_EXPIRED: string
}